[package]
name = "mruby-sys"
version = "0.1.0"
authors = ["Matt McDonald <mail.matt.mcdonald@gmail.com>"]
edition = "2018"
links = "mruby"
build = "build.rs"

[dependencies]

[build-dependencies]
bindgen = "0.49.2"
